### ISSUE TITLE
Delayed::DeserializationError

### ISSUE THREAD

**Issue by ajsharp** [appelier/bigtuna#50]
I get the following error when I try to build a project after deleting failed or hung builds. Not exactly sure what's happening here, but it seems like something is getting corrupted in DelayedJob. It would be nice to have some sort of "big red button" clear the job queue feature. 

```
Delayed::DeserializationError (Delayed::DeserializationError):
  app/models/project.rb:142:in `remove_project_jobs_in_queue'
  app/models/project.rb:141:in `each'
  app/models/project.rb:141:in `remove_project_jobs_in_queue'
  app/models/project.rb:45:in `build!'
  app/models/project.rb:42:in `build!'
  app/controllers/projects_controller.rb:22:in `build'
```

**Comment by bobzhang199102** [comment]
@ypadlyak have you solved that issue?

**Comment by ypadlyak** [comment]
The Project seems to be down now. We have switched to Gitlab a long time ago
